language: ruby
cache: bundler
rvm:
  - 1.8.7
  - 1.9.3
services:
  - mongodb
  - memcached
  - redis-server
notifications:
  email: false
  # hipchat:
  #  rooms:
  #    - 68c40f24dcfeeaf8ddb07cd32fe150@ZerigoDNS
  #  template:
  #    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Diff</a>)'
  #  format: html